#!/bin/bash
PRIX_ANANAS=30
PRIX_BANANE=4
PRIX_MELON=17
PRIX_PANIER=0
POURBOIRE=2
#Prix attendu : 91 
TOTAL=$(($PRIX_ANANAS + 2* $PRIX_BANANE + 3 * $PRIX_MELON + $PRIX_PANIER + $POURBOIRE))
echo "Total panier: $TOTAL"
